#!/bin/sh
# PROVIDE: unlockgeli
# REQUIRE: netwait
# BEFORE: jail

. /etc/rc.subr

name=unlockgeli
rcvar=unlockgeli_enable

start_cmd="${name}_start"
stop_cmd=":"

load_rc_config $name
: ${unlockgeli:=no} 

dummy_start()
{
	eval pools=\${$@:-${unlockgeli_pools}}
	for _g in $pools; do
		eval devs=\${unlockgeli_${_g}_devs}
		eval key=\${unlockgeli_${_g}_key}
		eval key_identityfile=\${unlockgeli_${_g}_identityfile}
		eval key_username=\${unlockgeli_${_g}_username}
		eval passphrase=\${unlockgeli_${_g}_passphrase}
		eval passphrase_identityfile=\${unlockgeli_${_g}_identityfile}
		eval passphrase_username=\${unlockgeli_${_g}_username}

		keytempfile=/tmp/unlockgeli.key.tmp
		pwtempfile=/tmp/unlockgeli.pw.tmp
		scp -i ${key_identityfile} ${key_username}@${key} $keytempfile
		scp -i ${passphrase_identityfile} ${passphrase_username}@${passphrase} $pwtempfile
		for _d in ${group_devs}; do
			geli attach -k $keytempfile -j $pwtempfile $_d
		done
		rm -f $keytempfile
		rm -f $pwtempfile

		zfs mount -a
	done
}

case $# in
1)	run_rc_command $@ ${geliunlock_list:-_ALL} ;;
*)	run_rc_command $@ ;;
esac
